networks:
  net5g:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

services:
  amf:
    build: ../amf
    container_name: amf
    command: ["/usr/local/bin/amf", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/amfcfg.yaml:/app/config.yaml
    ports:
      - "8001:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.10
    depends_on:
      - mongodb
      - nrf
    environment:
      - MANAGED_BY_CONFIG_POD: "true"

  ausf:
    build: ../ausf
    container_name: ausf
    command: ["/usr/local/bin/ausf", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/ausfcfg.yaml:/app/config.yaml
    ports:
      - "8002:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.11
    depends_on:
      - mongodb
      - nrf

  nrf:
    build: ../nrf
    container_name: nrf
    command: ["/usr/local/bin/nrf", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/nrfcfg.yaml:/app/config.yaml
    ports:
      - "8003:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.12
    depends_on:
      - mongodb

  simapp:
    build: ../simapp
    container_name: simapp
    command: ["/usr/local/bin/simapp", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/simapp.yaml:/app/config.yaml
    ports:
      - "8010:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.56
    depends_on:
      - webui

  nssf:
    build: ../nssf
    container_name: nssf
    command: ["/usr/local/bin/nssf", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/test_nssf_config.yaml:/app/config.yaml
    ports:
      - "8004:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.13
    depends_on:
      - mongodb
      - nrf

  pcf:
    build: ../pcf
    container_name: pcf
    command: ["/usr/local/bin/pcf", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/pcfcfg.yaml:/app/config.yaml
    ports:
      - "8005:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.14
    depends_on:
      - mongodb
      - nrf

  smf:
    build: ../smf
    container_name: smf
    command: ["/usr/local/bin/smf", "--cfg", "/app/config.yaml", "-uerouting", "/app/uerouting.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/smfcfg.yaml:/app/config.yaml
      - ../configs_files/docker_compose_config_notsim/uerouting.yaml:/app/uerouting.yaml
    ports:
      - "8006:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.15
    depends_on:
      - mongodb
      - nrf

  upfadapter:
    build: ../upfadapter
    container_name: upf-adapter
    command: ["/usr/local/bin/upfadapter"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/upfadapter.yaml:/app/config.yaml
    ports:
      - "8009:8090"
    networks:
      net5g:
        ipv4_address: 172.18.0.21

  udm:
    build: ../udm
    container_name: udm
    command: ["/usr/local/bin/udm", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/udmcfg.yaml:/app/config.yaml
    ports:
      - "8007:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.16
    depends_on:
      - mongodb
      - nrf

  udr:
    build: ../udr
    container_name: udr
    command: ["/usr/local/bin/udr", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/udr_config.yaml:/app/config.yaml
    ports:
      - "8008:8000"
    networks:
      net5g:
        ipv4_address: 172.18.0.17
    depends_on:
      - mongodb
      - nrf

  webui:
    build: ../webconsole
    container_name: webui
    command: ["/usr/local/bin/webconsole-ui", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/webuicfg.yaml:/app/config.yaml
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      net5g:
        ipv4_address: 172.18.0.18
    depends_on:
      - mongodb
  
  gnbsim:
    build: ../gnbsim
    container_name: gnbsim
    command: ["/usr/local/bin/gnbsim", "--cfg", "/app/config.yaml"]
    volumes:
      - ../configs_files/docker_compose_config_notsim/gnbsim.yaml:/app/config.yaml
    ports:
      - "8083:8080"
    networks:
      - net5g
    depends_on:
      - amf
    restart: unless-stopped

  nettools:
    image: nicolaka/netshoot:latest
    container_name: nettools
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    networks:
      net5g:
        ipv4_address: 172.18.0.22
    # Herramientas de red para testeo interno

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: admin
    networks:
      net5g:
        ipv4_address: 172.18.0.30

  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - mongodb
    volumes:
      - ./mongo-setup.sh:/mongo-setup.sh
    entrypoint: ["bash", "/mongo-setup.sh"]
    networks:
      net5g:
        ipv4_address: 172.18.0.31

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb
      - mongo-setup
    networks:
      net5g:
        ipv4_address: 172.18.0.32
volumes:
  kafka_data:
