networks:
  net5g:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1  
services:  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo1_data:/data/db
    networks:
      net5g:
        ipv4_address: 172.18.0.30

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - ./mongo2_data:/data/db
    networks:
      net5g:
        ipv4_address: 172.18.0.31

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - ./mongo3_data:/data/db
    networks:
      net5g:
        ipv4_address: 172.18.0.32

  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - mongodb
      - mongo2
      - mongo3
    volumes:
      - ./mongo-setup.sh:/mongo-setup.sh
    entrypoint: ["bash", "/mongo-setup.sh"]
    networks:
      net5g:
        ipv4_address: 172.18.0.33

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb
      - mongo-setup
    networks:
      net5g:
        ipv4_address: 172.18.0.34